werkzeug - WARNING -  * Debugger is active!
werkzeug - INFO -  * Debugger PIN: 308-273-549
werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
werkzeug - INFO -  * Running on http://192.168.1.5:8080/ (Press CTRL+C to quit)
werkzeug - INFO -  * Detected change in 'D:\\Projects\\DockerDjango\\coding_challenge\\backend\\app.py', reloading
werkzeug - WARNING -  * Debugger is active!
werkzeug - INFO -  * Debugger PIN: 308-273-549
werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
werkzeug - INFO -  * Running on http://192.168.1.5:8080/ (Press CTRL+C to quit)
werkzeug - INFO -  * Detected change in 'D:\\Projects\\DockerDjango\\coding_challenge\\backend\\app.py', reloading
werkzeug - WARNING -  * Debugger is active!
werkzeug - INFO -  * Debugger PIN: 308-273-549
werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
werkzeug - INFO -  * Running on http://192.168.1.5:8080/ (Press CTRL+C to quit)
root - ERROR - Report Random Objects Exception: [Errno 2] No such file or directory: '1636567170.csv'
Traceback (most recent call last):
  File "D:\Projects\DockerDjango\coding_challenge\backend\app.py", line 68, in report_random_objects
    file_cursor = open(request.args.get(constants.ARGS_FILE_PARAM), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '1636567170.csv'
werkzeug - INFO - 127.0.0.1 - - [10/Nov/2021 23:21:15] "GET /report_rdm_objects?filename=1636567170.csv HTTP/1.1" 200 -
werkzeug - INFO -  * Restarting with stat
werkzeug - WARNING -  * Debugger is active!
werkzeug - INFO -  * Debugger PIN: 104-181-486
werkzeug - WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
werkzeug - INFO -  * Running on http://192.168.1.5:8080/ (Press CTRL+C to quit)
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 12:47:03] "GET /generate_rdm_objects HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 12:47:12] "GET /generate_rdm_objects HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 12:48:14] "GET /generate_rdm_objects HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 12:49:27] "GET /generate_rdm_objects HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 12:50:24] "GET /generate_rdm_objects HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 12:50:58] "GET /generate_rdm_objects HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 12:51:18] "GET /generate_rdm_objects HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 12:53:36] "GET /generate_rdm_objects HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 12:55:45] "GET /generate_rdm_objects HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 12:56:40] "GET /generate_rdm_objects HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 12:56:43] "GET /download_rdm_objects?filename=1636617400.csv HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 12:59:12] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 12:59:15] "GET /download_rdm_objects?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 12:59:15] "GET /download_rdm_objects?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 12:59:15] "GET /download_rdm_objects?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 12:59:15] "GET /download_rdm_objects?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 13:15:22] "GET /generate_rdm_objects HTTP/1.1" 200 -
root - ERROR - Report Random Objects Exception: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "D:\Projects\DockerDjango\coding_challenge\backend\app.py", line 68, in report_random_objects
    file_cursor = open(request.args.get(constants.ARGS_FILE_PARAM), 'r')
TypeError: expected str, bytes or os.PathLike object, not NoneType
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 13:15:25] "GET /report_rdm_objects?http://127.0.0.1:8080/download_rdm_objects,filename=1636618521.csv HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 13:47:42] "GET /generate_rdm_objects HTTP/1.1" 200 -
root - ERROR - Report Random Objects Exception: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "D:\Projects\DockerDjango\coding_challenge\backend\app.py", line 68, in report_random_objects
    file_cursor = open(request.args.get(constants.ARGS_FILE_PARAM), 'r')
TypeError: expected str, bytes or os.PathLike object, not NoneType
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 13:47:43] "GET /report_rdm_objects?http://127.0.0.1:8080/download_rdm_objects,filename=1636620462.csv HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 13:48:17] "GET /generate_rdm_objects HTTP/1.1" 200 -
root - ERROR - Report Random Objects Exception: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "D:\Projects\DockerDjango\coding_challenge\backend\app.py", line 68, in report_random_objects
    file_cursor = open(request.args.get(constants.ARGS_FILE_PARAM), 'r')
TypeError: expected str, bytes or os.PathLike object, not NoneType
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 13:48:18] "GET /report_rdm_objects?http://127.0.0.1:8080/download_rdm_objects,filename=1636620497.csv HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 13:49:51] "GET /generate_rdm_objects HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 13:49:53] "GET /report_rdm_objects?filename=1636620591.csv HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 14:11:47] "GET /generate_rdm_objects HTTP/1.1" 200 -
werkzeug - INFO - 127.0.0.1 - - [11/Nov/2021 14:11:50] "GET /report_rdm_objects?filename=1636621907.csv HTTP/1.1" 200 -
